config/apps/core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('movies/', views.MovieListView.as_view(), name='movie_list'),
    path('movie/<int:pk>/',
         views.MovieDetailView.as_view(), name='movie_detail'),
    path('persons/<int:pk>/',
         views.PersonDetail.as_view(), name='person_detail'),
    path('movie/<int:movie_id>/vote/',
         views.CreateVote.as_view(), name='vote_create'),
    path('movie/<int:movie_id>/vote/<int:pk>/',
         views.UpdateVote.as_view(), name='vote_update'),
    path('movie/<int:movie_id>/image/upload/',
         views.MovieImageUpload.as_view(), name='movie_imageupload'),
    path('movie/top10movies/', views.TopMovies.as_view(), name='top_movies'),
]

config/apps/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'user'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

config/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

MEDIA_FILE_PATHS = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('apps.user.urls', namespace='user')),
    path('', include('apps.core.urls', namespace='core')),
] + MEDIA_FILE_PATHS

config/apps/core/models.py
from uuid import uuid4

from django.db import models
from django.db.models.aggregates import Sum

from django.conf import settings


class MovieManager(models.Manager):
    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related('director')
        qs = qs.prefetch_related('writers', 'actors')
        return qs

    def all_with_related_persons_and_score(self):
        qs = self.all_with_related_persons()
        qs = qs.annotate(score=Sum('vote__value'))
        return qs

    def top_movies(self, limit=10):
        qs = self.get_queryset()
        qs = qs.annotate(vote_sum=Sum('vote__value'))
        qs = qs.exclude(vote_sum=None)
        qs = qs.order_by('-vote_sum')
        return qs[:limit]


class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audiences'),
        (RATED_PG, 'PG - Parental Guidance'),
        (RATED_R, 'R - Restricted'),
    )

    title = models.CharField(max_length=140)
    director = models.ForeignKey(
        to='Person',
        on_delete=models.SET_NULL,
        related_name='directed',
        null=True,
        blank=True,
    )
    writers = models.ManyToManyField(
        to='Person',
        related_name='writing_credits',
        blank=True,
    )
    actors = models.ManyToManyField(
        to='Person',
        through='Role',
        related_name='acting_credits',
        blank=True,
    )
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(choices=RATINGS, default=NOT_RATED)
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)
    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} ({})'.format(self.title, self.year)


class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related(
            'directed',
            'writing_credits',
            'role_set__movie'
        )


class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)
    objects = PersonManager()

    class Meta:
        ordering = ('last_name', 'first_name')

    def __str__(self):
        if self.died:
            return '{}, {}   ({} - {})'.format(
                self.last_name, self.first_name, self.born, self.died,
            )
        return '{}, {}   ({})'.format(
            self.last_name, self.first_name, self.born
        )


class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return '{}  {}  {}'.format(self.movie_id, self.person_id, self.name)

    class Meta:
        unique_together = (
            'movie',
            'person',
            'name',
        )


class VoteManager(models.Manager):
    def get_vote_or_unsaved_blank_vote(self, movie, user):
        try:
            return Vote.objects.get(
                movie=movie, user=user
            )
        except Vote.DoesNotExist:
            return Vote(movie=movie, user=user)


class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = (
        (UP, '👍👍👍\U0001F44D👍👍👍👍'),
        (DOWN, '\U0001F44E'),
    )

    value = models.SmallIntegerField(choices=VALUE_CHOICES)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)
    objects = VoteManager()

    class Meta:
        unique_together = ('user', 'movie')

    def __str__(self):
        return '{} - {}'.format(self.movie.title, self.user.username)


def movie_directory_path_with_uuid(instance, filename):
    return '{}/{}'.format(instance.movie_id, uuid4())


class MovieImage(models.Model):
    image = models.ImageField(upload_to=movie_directory_path_with_uuid)
    uploaded = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey(
        to='Movie', on_delete=models.CASCADE, related_name='images')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

config/apps/core/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Vote, Movie, MovieImage


class VoteForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,
    )
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True,
    )
    value = forms.ChoiceField(
        label='Vote',
        widget=forms.RadioSelect,
        choices=Vote.VALUE_CHOICES,
    )

    class Meta:
        model = Vote
        fields = ('value', 'user', 'movie',)


class MovieImageForm(forms.ModelForm):
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True,
    )
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,
    )

    class Meta:
        model = MovieImage
        fields = ['image', 'user', 'movie']

config/apps/core/views.py
import django

from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.cache import cache

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView

from .forms import VoteForm, MovieImageForm
from .models import Movie, Person, Vote
from .mixins import CachePageVaryOnCookieMixin


class MovieListView(ListView):
    model = Movie
    paginate_by = 10
    queryset = Movie.objects.all().order_by('title')


class TopMovies(CachePageVaryOnCookieMixin, ListView):
    cache_name = 'default'
    template_name = 'core/topmovies_list.html'

    def get_queryset(self):
        limit = 10
        key = 'top_movies_%s' % limit
        cached_qs = cache.get(key)
        if cached_qs:
            same_django = cached_qs._django_version == django.get_version()
            if same_django:
                return cached_qs
        qs = Movie.objects.top_movies(limit=limit)
        cache.set(key, qs)
        return qs


class MovieDetailView(DetailView):
    queryset = Movie.objects.all_with_related_persons_and_score()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['image_form'] = self.movie_image_form()
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                movie=self.object, user=self.request.user,
            )
            if vote.id:
                vote_form_url = reverse('core:vote_update', kwargs={
                    'movie_id': vote.movie.id, 'pk': vote.id})
            else:
                vote_form_url = (
                    reverse(
                        'core:vote_create', kwargs={'movie_id': self.object.id})
                )
            vote_form = VoteForm(instance=vote)
            context['vote_form'] = vote_form
            context['vote_form_url'] = vote_form_url
        return context

    def movie_image_form(self):
        if self.request.user.is_authenticated:
            return MovieImageForm()
        return None


class PersonDetail(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse('core:movie_detail', kwargs={'pk': movie_id})

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse('core:movie_detail', kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object()
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied('cannot change another users vote.')
        return vote

    def get_success_url(self):
        movie_id =  self.object.movie.id
        return reverse('core:movie_detail', kwargs={'pk': movie_id})

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse('core;movie_detail', kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)


class MovieImageUpload(LoginRequiredMixin, CreateView):
    form_class = MovieImageForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def render_to_response(self, context, **response_kwargs):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse('core:movie_detail', kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)

    def get_success_url(self):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse('core:movie_detail', kwargs={'pk': movie_id})
        return movie_detail_url

config/apps/core/templates/core/movie_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ object.title }} - {{ block.super }}
{% endblock %}


{% block main %}
    <h1> {{ object }} </h1>
    <p class="lead">{{ object.plot }}</p>
        <ul class="movie-image list-inline">
        <div class="row">
            {% for image in object.images.all %}
                <div class="col-md-4 col-lg-4 mx-2">
                    <li class="list-inline-item">
                <img src="{{ image.image.url }}" class=" img-thumbnail">
                </div>
            </li>
        {% endfor %}
        </div>
    </ul>
    <p>Directed by: {{ object.director }}</p>
{% endblock %}

{% block sidebar %}
    <div>
        This movie is rated:
        <span class="badge badge-primary">
            {{ object.get_rating_display }}
        </span>
    </div>
    <div>
        <h2>Upload New Image:</h2>
        <form method="POST" enctype="multipart/form-data"
              action="{% url 'core:movie_imageupload' movie_id=object.id %}">
            {% csrf_token %}
            {{ image_form.as_p }}
            <p>
                <button class="btn btn-primary">Upload!</button>
            </p>
        </form>
    </div>
    <div>
        <h2>Score: {{ object.score|default_if_none:"TBD" }}</h2>
    </div>
    <div>
        {% if vote_form %}
            <form method="POST" action="{{ vote_form_url }}">
                {% csrf_token %}
                {{ vote_form.as_p }}
                <button class="btn btn-primary" type="submit">Vote</button>
            </form>
        {% else %}
            <p>Log in to vote for this movie.</p>
            <a href="{% url 'user:login' %}" class="btn btn-primary">Login</a>
        {% endif %}
    </div>
{% endblock %}

config/apps/core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block main %}
    <ul>
        {% for movie in object_list %}
            <li>
                <a href="{% url 'core:movie_detail' movie.id %}">
                    {{ movie.title }}
                </a>
            </li>
        {% endfor %}
    </ul>
    {% if is_paginated %}
        <nav>
            <ul class="pagination">
                <li class="page-item">
                    <a href="{% url 'core:movie_list' %}?page=1" class="page-link">
                        First
                    </a>
                </li>

                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a href="{% url 'core:movie_list' %}?page={{page_obj.previous_page_number}}"
                           class="page-link">
                            {{ page_obj.previous_page_number }}
                        </a>
                    </li>
                {% endif %}
                <li class="page-item active">
                    <a href="{% url 'core:movie_list'  %}?page={{ page_obj.number }}"
                       class="page-link">
                        {{ page_obj.number }}
                    </a>
                </li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="{% url 'core:movie_list' %}?page={{ page_obj.next_page_number }}"
                           class="page-link">
                            {{ page_obj.next_page_number }}
                        </a>
                    </li>
                {% endif %}
                <li class="page-item">
                    <a href="{% url 'core:movie_list' %}?page=last"
                       class="page-link">
                        Last
                    </a>
                </li>
            </ul>
        </nav>
    {% endif %}

{% endblock main %}

config/apps/core/templates/core/person_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.first_name }}
    {{ object.last_name }}
{% endblock %}

{% block main %}
    <h1> {{object}} </h1>
    <h2>Actor</h2>
    <ul>
        {% for role in object.role_set.all %}
            <li>
                <a href="{% url 'core:movie_detail' role.movie.id %}">
                    {{ role.movie }}
                </a>:
                {{ role.name }}
            </li>
        {% endfor %}
    </ul>
    <h2>Writer</h2>
    <ul>
        {% for movie in object.writing_credits.all %}
            <li>
                <a href="{% url 'core:movie_detail' movie.id %}">
                    {{ movie }}
                </a>
            </li>
        {% endfor %}
    </ul>
    <h2>Director</h2>
    <ul>
        {% for movie in object.directed.all %}
            <li>
                <a href="{% url 'core:movie_detail' movie.id %}">
                    {{ movie }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

config/apps/core/templates/core/topmovies_list.html
{% extends 'base.html' %}
{% load cache %}

{% block title %}
    Top 10 Movies
{% endblock %}

{% block main %}
    <h1>Top 10 Movies</h1>
    <ol>
        {% for movie in object_list %}
            <li>
                <a href="{% url 'core:movie_detail' movie.id %}"> {{ movie }} </a>
            </li>
        {% endfor %}
    </ol>
{% endblock %}